name: Nexus Engine - Guardião de Código

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar o Ambiente Java (JDK 25)
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'oracle'
        cache: 'maven'

    - name: Validar e Compilar Código Java
      run: mvn clean verify -DskipTests
